# Change these first
owner: marci4server # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository
runner: [self-hosted]

sites:
  - name: marci4.de
    url: https://marci4.de
  - name: Plesk
    url: $PLESK
  - name: Nextcloud
    url: $NEXTCLOUD
  - name: gfl.marci4.de
    url: https://gfl.marci4.de
  - name: bot.marci4.de
    url: https://bot.marci4.de
  - name: bot.marci4.de - WebSocket
    url: https://bot.marci4.de:8081
    __dangerous__disable_verify_peer: true
    expectedStatusCodes:
      - 404
  - name: feuerwehr-lauben.de
    url: https://feuerwehr-lauben.de
  - name: kljb-lauben.de
    url: https://kljb-lauben.de
  - name: elektro-oppold.de
    url: https://elektro-oppold.de
  - name: faschingsverein-oy.de
    url: https://faschingsverein-oy.de
  - name: musikfest-2020.de
    url: https://musikfest-2020.de/
  - name: saegesucht.de
    url: https://saegesucht.de
  - name: sw-vt.de
    url: https://sw-vt.de/
  - name: prinzessin-gugelhupf.de
    url: https://prinzessin-gugelhupf.de/
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  introTitle: "Status page"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
